import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "About & content policy",
  description: "How Metacritic-al creates original movie satire and fictional review-card metrics.",
};

export default function AboutPage() {
  return (
    <main className="about-shell">
      <article className="glass-panel about-panel">
        <Link className="about-back" href="/">← Back to the studio</Link>
        <p className="landing-kicker">A note from the projection booth</p>
        <h1>About Metacritic-al</h1>
        <p className="about-lede">A locally served movie-roast generator with no hosted backend. It turns a film title, a critic persona and a little heat into original, deterministic satire.</p>

        <h2>Content policy</h2>
        <ul>
          <li>We roast films and fictional taste takes, never a person’s body, identity, health or private life.</li>
          <li>We avoid protected-class jokes, slurs, threats and sexual content.</li>
          <li>Review text is original. Plot points and scenes may be paraphrased; dialogue, lyrics and published reviews are not reproduced.</li>
          <li>Film titles and names are treated as text. The app is independent and is not affiliated with filmmakers, studios or review platforms.</li>
        </ul>

        <h2>The numbers are fictional</h2>
        <p>Reviewers, ratings, watched times, likes and comments are generated for the joke. They do not describe real people, audience activity or an official film score. The same inputs produce the same card so a shared link can replay it.</p>
        <h2>Credits</h2>
        <p>This demo uses TMDB movie metadata and images when available. Review-card text is generated by Metacritic-al and is original; it is not copied from TMDB reviews.</p>
        <div className="tmdb-credit">
          <a href="https://www.themoviedb.org" target="_blank" rel="noreferrer noopener" aria-label="The Movie Database (TMDB), opens in a new tab">
            <Image src="/tmdb-logo.svg" width={150} height={13} alt="TMDB" />
          </a>
          <p className="tmdb-disclaimer">This product uses the TMDB API but is not endorsed or certified by TMDB.</p>
        </div>
        <p className="about-note">TMDB movie metadata and images are supplied by TMDB. Review text, usernames, ratings, and engagement counters on the card are original or fictional app output.</p>
        <Link className="about-cta" href="/">Make a review</Link>
      </article>
    </main>
  );
}
